version: "3.9"

services:
    nginx:
        container_name: codeigniter-nginx
        image: nginx:latest
        ports:
            - "8010:80"
        volumes:
            - ../www:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        container_name: codeigniter-php-fpm
        volumes:
            - ../www:/var/www/html
        build: ./php-fpm
        command: /root/run.sh
